# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Write-Host "Hello World"
      dir

      cd .\Kabatra.Countdown.Numbers
      dir
#- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'
  
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#    projects: |
#      ./Kabatra.Countdown.Numbers/Kabatra.Countdown.Numbers.sln

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'test'